spectrochempy/spectrochempy

.ci/env/scpy3.7.yml
conda/meta.yaml
env/scpy-dev.yml
env/scpy.yml
requirements.txt

this provisionally fixs docrep version to 0.2.7, until the docstring
related code is modified within spectrochempy

BUG FIX #133 docrep version

---

.travis.yml

Just forgot that anaconda upload does not work with 3.9

FIX: conda build

---

docs/conf.py

Fix an error while building documentation:
File "/home/travis/build/spectrochempy/spectrochempy/docs/conf.py", line 632, in setup
app.add_stylesheet("theme_override.css")  # also can be a full URL
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'

FIX: Error in build doc

---

spectrochempy/core/readers/readomnic.py

This is what we figured out so far. Inferograms are similar to absorbance data:
```java
int start;
int size;
skipBytes(8);
int end ;
seek(start);
int signals = size / 4;
rawSignals = new double[signals];
```
Rotation angle is:
```java
skipBytes(1);
double rotationAngle = read2BUIntegerLE();
```

Documented more .spa header keys.

---

spectrochempy/core/dataset/coordset.py
tests/test_dataset/test_ndcoordset.py

the order of multicoordinates for a single dimension was changed
after fixing issue #310.

FIX: the order of multicoordinates for a single dimension

---

CHANGELOG.md
spectrochempy/utils/file.py
tests/test_core/test_writers/test_exporter.py

dataset.write('filename')
-> open dialog if 'filename' does not exists
-> overwrite if it exists,
except if keyword save_as=True.
-> now if save_as=true and filename exists,
and confirm=False will also overwrite without dialog.
By default
confirm=True, save_as=False
- [ X] Closes #360 
- [ X] Tests updated 
- [ X] CHANGELOG.md updated

FIX issue #360

---

CHANGELOG.md
spectrochempy/core/dataset/ndarray.py
tests/test_core/test_dataset/test_dataset.py

FIX: bug with units transformation between transmittance, absorbance and abs.transmittance

---

CHANGELOG.md
scripts/validate_docstrings.py
spectrochempy/core/dataset/coordset.py
spectrochempy/core/processors/concatenate.py
spectrochempy/core/readers/importer.py
tests/test_core/test_processors/test_concatenate.py
tests/test_core/test_readers/test_read_zip.py

Concatenate now scales linearly with the number of datasets
NB 
- `force_stack` keyword in concatenate() amounted to stack(), it is now deprecated. 
- `stack()` method now generates a new dim, even if a dim of size one is present, so that it resembles more to the the stack() methods of numpy or xarray
- `concatenate()` now can only be used on existing dimension

refactor concatenate (see #408)

---

spectrochempy/application.py

Fixed an issue when a custom datadir path is set. It is stored in a .spectrochempy/config/GeneralPreferences.json file to replace the default setting.However, when it is read at the initialization of a new session, it is read as a string, which has to be converted to a Path to use for example the read_remote method. That's what this fix does automatically.

FIX: datadir as Path whenever it is read form a json config file.

---

tests/conftest.py

When running test, conftest was downloading data. But even if the data were already downloaded, the fact of checking online, was taking too much time.

FIX: accelerate tests when testdata have already been downloaded.

---

CHANGELOG.md
docs/userguide/reference/api.rst
spectrochempy/analysis/simplisma.py
spectrochempy/core/readers/importer.py
spectrochempy/core/readers/read_omnic.py
spectrochempy/core/readers/read_soc.py
tests/test_core/test_readers/test_read_soc.py

Add Surface optics reader
Deprecate verbose option in simplisma for consistency with mcarls
Put back `__init__.py` in test_readers (caused an error on my fork for tests with py 3.9)

SOC reader, simplisma, fix

---

.github/workflows/publish_new_release.yml
CHANGELOG.md

Workflow was not publishing correctly on pypi and anaconda due to the fact that  Build_package workflow wasn't trigerred  on publishing release. 
To try fixing this problem, I will try to automatically create a draft release: Publishing the final release will be done manually by clicking on publishing on the release page..

FIX: publish a draft release

---

.ci/env_template.yml
.gitignore

For exemple Docstring tests were not working with 3.10.4.
In this commit I remove pinning of sphinx version and other sphinx related package (nbspinx, and sphinx-gallery).

FIX: sphinx related problems with python version > 3.10

---

spectrochempy/core/__init__.py

Reverts spectrochempy/spectrochempy#488 because pypi build failed.

Revert "FIX: add nice message when tkinter no installed"

---

.github/workflows/build_docs.yml
.github/workflows/build_package.yml
.github/workflows/draft_new_release.yml
.github/workflows/pre-commit.yml
.github/workflows/test_package.yml

This fixes the deprecation warnings issued on nightly bulds and tests
The warning on conda upfdate persists,

Update versions of GH actions

---

.github/workflows/build_package.yml

For some reason, the previous ANACONDA_UPLOAD_TOKEN pointed to Anaconda.org ATravert account (???). So, I created a new token ANACONDA_API_TOKEN (user Spectrocat) and updated the GitHub setting and the workflow accordingly.

FIX: ANACONDA upload

---

.ci/templates/dependencies.tmpl
environment_dev.yml
requirements_dev.txt

Sphinx6 remove logo and favicon for html doc build with sphinx_rtd_theme theme.

FIX: pin sphinx to 5.3 and sphinx_rtd_theme to 1.1

---

spectrochempy/application.py

Restore two missing functions that were commented for testing during the recent modifications of the log system, but never restored.
Now the scp.set_loglevel method should work!

FIX: log_level property functions removed by mistake

---

spectrochempy/analysis/_base.py

Change labels from #1, #2... to #0, #1 etc... for consistency with component indexing
Make a little easier to identify components on a plot and find the correct indice.

Change labels from #1, #2... to #0, #1 etc... for consistency.

---

spectrochempy/analysis/efa.py
spectrochempy/analysis/mcrals.py
spectrochempy/analysis/nmf.py
spectrochempy/analysis/pca.py
spectrochempy/analysis/simplisma.py

standardization of some elements such as 
*some indentations 
*single quote for strings when in the description part of the docstrings, 
*double/single backsticks for emphasis or references. 
*replace :code: by simple double backsticks as there is no difference in the style in the final output.
*modify the two new deprecations (property to parameter)

MAINT: mcrals doc cleaning

---

docs/reference/index.rst
docs/whatsnew/changelog.rst
docs/whatsnew/latest.rst
spectrochempy/core/__init__.py
spectrochempy/core/dataset/baseobjects/ndarray.py
spectrochempy/processing/baseline/baseline.py
spectrochempy/processing/fft/shift.py
spectrochempy/utils/baseconfigurable.py
spectrochempy/utils/metaconfigurable.py
tests/test_analysis/test_decomposition/test_mcrals.py

When used as a decorator the signature of the function was wrongly changed.
This PR also deprecates `parameters` method of configurable in favor of `params` (in order to avoid conflict with other usage of this keyword)

FIX: docs problem with the `@_docstring.get_docstring` decorator.

---

.ci/templates/dependencies.tmpl
.ci/templates/meta.tmpl
.conda/meta.yaml
.github/workflows/test_package.yml
.pylintrc
Dockerfile
docs/gettingstarted/install/index.rst
docs/gettingstarted/install/install_sources.rst
environment.yml
environment_dev.yml
environment_test.yml
requirements/requirements.txt
requirements/requirements_dev.txt
requirements/requirements_test.txt
setup.py
spectrochempy/application/plot_preferences.py
spectrochempy/core/dataset/nddataset.py
spectrochempy/processing/transformation/concatenate.py
spectrochempy/utils/datetimeutils.py
spectrochempy/utils/testing.py
tests/test_core/test_dataset/test_coord.py
tests/test_core/test_dataset/test_dataset.py
tests/test_core/test_dataset/test_ndmath.py
tests/test_utils/test_testing.py

Changes : 
* `pytz` library is replaced by the `zoneinfo` available since py3.9.
The change is now possible sine collaborators works with 3.10. 
* make testing assert more unifom. 
**Checklist**:

MAINT: remove pytz dependency

---

spectrochempy/analysis/decomposition/mcrals.py

the correction for nonnegative spectra was missing 
**Checklist**:

FIX nonnegative spectra in MCRALS

---

.ci/templates/dependencies.tmpl
.conda/meta.yaml
environment.yml
environment_dev.yml
environment_test.yml
requirements/requirements.txt
requirements/requirements_dev.txt
requirements/requirements_test.txt
spectrochempy/__init__.py

Ssome incompatibilities with NumPy 2.0 (relaeased June 16thj 2024), e.g.: 
- visibleDeprecationWarning now in exceptions.VisibleDeprecationWarning (not from base name)
- pint not compatible yetr 
- ...
numpy version is temporarily pinned to <=2.0.0
**Checklist**:

fix numpy compatibility

---

src/spectrochempy/utils/print.py
tests/test_core/test_dataset/test_coord.py
tests/test_processing/test_fft/test_nmr.py

html 'blue' has very low contrast with dark mode (and green, but in a lesser extent). This PR replaces these colors by blue and green that are compatible with both light and dark modes.

adapt html colors to dark  mode

---

docs/sources/userguide/objects/dataset/dataset.py
docs/sources/whatsnew/changelog.rst
src/spectrochempy/core/dataset/coordset.py
tests/test_core/test_dataset/test_coordset.py

fix to issue #696.
Now the subtraction on multicoordinates works transparently. 
Note  that all coordinates (not only the default) are subtracted;  which I think has the advantage to be consistent with the slicing. If `ds.y` is a multicoordinate,  `ds.y[0]` returns a multiocoordinate, and one would expect that `ds.y - ds.y[0]`  subtracts all the coordinates ?
In practice, I agree that the user would certainly prefer to make the subtraction on one of the coordinates, but in this case it is probably better that he makes it explicitely ?, i.e. `ds.y_1 - ds.y_1[0]` 
maybe it would be worthwhile adding something about this in the user guide ?
**Checklist**:
if you have one) in the zenodo.json in the field contributors field. _Be careful
not to break the json format (check the content of the …

fix to issue #696 coordset subtraction

---

.github/workflows/install_on_colab.yml
docs/sources/whatsnew/changelog.rst
docs/sources/whatsnew/latest.rst
src/spectrochempy/core/readers/read_omnic.py

In some srs files, the absorbance/intensity data are recorded from low to high wavenumbers, i.e. in the reverse order as compared to most cases (... all cases know by us until issue #858). We don't know yet how to determine this inversion from the srs file. So the current fix consists in adding an adhoc option  'reverse_x' which reverses the data ordering along the x axis: `data = data[:,::-1]`  
As only one case has been reported for the moment we do not add a specific test
**Checklist**:

fix issue 858
