spectrochempy/spectrochempy

spectrochempy/core/dataset/ndarray.py
…itlets (so not from our code - should be fixed in Trailtlets)
=> FIX: #73 finished 

spectrochempy/core/readers/readopus.py
The modifications will lead to a correct result, whether the original brukeropusreader of the spectrochempy/brukeropusreader fork is used.
=> FIX #75  read_opus() shifts the xaxis

env/scpy-dev.yml, env/scpy-test-py3.6.yml, env/scpy-test-py3.7.yml, env/scpy-test-py3.8.yml, env/scpy-test.yml, env/scpy.yml, requirements.txt, spectrochempy/core/dataset/ndarray.py, spectrochempy/core/dataset/ndmath.py, spectrochempy/units/units.py, spectrochempy/utils/file.py, tests/test_dataset/test_ndmath.py, tests/test_units/test_units.py
* fixed problem with display _repr_html_ issues
* fixed problem with clip function (and units)
=> FIX: pint upgrade (issue #19)

spectrochempy/core/readers/readopus.py, tests/test_readers/test_read_opus.py
fix another bug and add test_opus_reader
=> FIX #76 read_opus() shifts the xaxis + test_opus_reader

.ci/scripts/conda-upload.sh, .ci/scripts/get-version.sh, .travis.yml
Make conda building, deploy and docs only when pushing on master branch.
Pull request should only run tests .
=> CI: continuing setup

.ci/scripts/conda-upload.sh, .ci/scripts/get-version.sh, .travis.yml
closes #75 #111 
Additional allow compilation of the pdf docs.
=> CI: Travis deploy and build doc improved 

.ci/env/scpy3.7.yml, .ci/scripts/conda-upload.sh, .ci/scripts/get-version.sh, .travis.yml, conda/meta.yaml, docs/api/analysis.rst, docs/api/index.rst, docs/api/inout.rst, pyproject.toml, setup.cfg, setup.py
after changes on setup.py conda build generated errors with setuptools_scm. Should be solved with this pull request.
=> CI: make conda build working again

spectrochempy/core/analysis/iris.py
This error sometime prevented the use of verbose=False flag in iris.py
=> FIX: an indentation error

.gitignore, setup.cfg, spectrochempy/__init__.py, spectrochempy/api.py, spectrochempy/application.py, spectrochempy/core/__init__.py, spectrochempy/scripts/scpy.py, spectrochempy/scripts/scpy_update.py, spectrochempy/utils/qtfiledialogs.py, spectrochempy/utils/system.py
Before it was sometimes a blocking process. Now update should be checked
only every 24h at the maximum and a non blocking subprocess is used
which open a Qt window to notice the user about update.
=> FIX: modify the way update are checked.

spectrochempy/units/units.py
Since the recent version of Pint, we go problems in HTML display
(docs and jupyter notebook). This is a tentative of solving this problem (Fix #131)
=> FIX: Unit display

docs/make.py
solves 2 errors related to the obtention of tag and issues from gitthub
=> FIX: build doc fails: make.py #138

tests/test_utils/test_system.py
=> FIX: attempt to fix an error during building

.travis.yml
mkdir spectrochempy_doc smissing
=> FIX: travis doc building

setup.py
This should fix a problem with twine and pypi.
=> FIX: setup relative paths

.travis.yml
Pypi need some work to be up to date. I prefer to stay with Conda only for the moment. Removed Pypi loading.
=> DEPLOY: removed pypi loading 

docs/_templates/layout.html, docs/conf.py, docs/gettingstarted/install/index.rst, docs/gettingstarted/install/install_adds.rst, docs/userguide/reference/changelog.rst
=> DOC: update doc and fix some links.

.travis.yml, spectrochempy/__init__.py, spectrochempy/application.py
=> Fix #239. Do not move the share/testdata directory nor symlink

CHANGELOG.md
=> Release 0.2.11

spectrochempy/core/plotters/plot2d.py, spectrochempy/core/processors/baseline.py, tests/test_dataset/test_dataset.py, tests/test_processors/test_baseline.py
Wasn't working on linux at least
=> FIX sequential baseline corrections

docs/userguide/analysis/peak_finding.py, spectrochempy/core/analysis/mcrals.py, spectrochempy/core/dataset/ndarray.py, spectrochempy/core/dataset/nddataset.py, spectrochempy/core/dataset/ndplot.py, spectrochempy/core/fitting/fit.py, spectrochempy/core/plotters/multiplot.py, spectrochempy/core/scripts/script.py, spectrochempy/databases/isotopes.py, spectrochempy/units/units.py, spectrochempy/utils/packages.py, spectrochempy/utils/plots.py, spectrochempy/utils/traits.py, spectrochempy/utils/zip.py, tests/test_dataset/test_dataset.py, tests/test_dataset/test_ndarray.py, tests/test_plotters/test_plot3D.py
* NDDataset and Coord constructor now accept data as an homogeneous list of Quantities (data with units)
* Indexing or slicing a NDDataset with Quantities is now possible
* matplotlib Axes are subclassed in order to accept methods with Quantities as arguments
=> New features

CHANGELOG.md, spectrochempy/utils/file.py
=> writer: add info when file overwritten

.github/ISSUE_TEMPLATE/config.yml
Discussions address should now be correct
=> Try to fix bug in one of the issue template

.ci/create_requirements.py, .ci/env_template.yml, .github/PULL_REQUEST_TEMPLATE.md, environment.yml, environment_dev.yml, requirements.txt, requirements_dev.txt
Updated and add more comments for the requirements and environment generation.
The requirements.txt should not be modified directly. Note that changes in this file
have no effect on the github action testing.
***All dependencies changes must be done in `.ci/env_template.yaml` to be taken into account by github actions.***
=> Updating environments

CHANGELOG.md, spectrochempy/core/dataset/ndplot.py, spectrochempy/core/plotters/plot1d.py, tests/test_core/test_plotters/test_plot_1D.py
=> Fix issue #375

spectrochempy/application.py
Log in debug mode wasn't working.
=> FIX: Change Log setting

CHANGELOG.md
[x] `CHANGELOG.md` updated for release 0.3.3
=> Release 0.3.3

.ci/env_template.yml, .conda/meta.yaml, .github/workflows/test_package.yml, .zenodo.json, CITATION.cff, environment_dev.yml, requirements_dev.txt, spectrochempy/utils/citation.py, tests/test_citations_cff.py
This Allows to have a possibility to cite this work from the github repository.
In addition this file and the zenodo metadata file is updated during tests (need to make a better workflow yet)
=> CITATION.cff added 

CHANGELOG.md, docs/gettingstarted/examples/fitting/plot_lstsq_single_equation.py, docs/userguide/reference/api.rst, spectrochempy/analysis/mcrals.py, spectrochempy/analysis/pca.py, tests/test_analysis/test_pca.py
other changes:
- update pre-commint with last vesion of black (generated an error) 
- reformat .py files accordingly
=> implement pca.reconstruct()

CHANGELOG.md, spectrochempy/core/processors/integrate.py
Cleaning: remove unecessary __init__.py files in tests directory.
Changelog cleaned.
=> prepare release 0.4.5

spectrochempy/core/dataset/ndio.py, spectrochempy/utils/jsonutils.py, tests/test_core/test_dataset/test_dataset.py
=> FIX: multicoordinate load/dump in scp format.

.ci/env_template.yml, .conda/meta.yaml, .gitignore, environment.yml, environment_dev.yml, requirements.txt, requirements_dev.txt
Pin jinja2 as it is the only difference I see between pip and conda version.
=> FIX: Try to fix install problem

CHANGELOG.md
- [X ] Close the #468 issue.
- Other changes reported in CHANGELOG.md
=> Prepare release 0.4.6.

spectrochempy/core/__init__.py
=> FIX: add nice message when tkinter no installed

.ci/env_template.yml, environment.yml, environment_dev.yml, requirements.txt, requirements_dev.txt
=> FIX: back to matplotlib pinned to 3.5

.ci/env_template.yml, .github/workflows/build_package.yml, environment.yml, environment_dev.yml, requirements.txt, requirements_dev.txt
Actually there is not problem with 3.6.2. Just be sure that there is no conflict with pip and conda installation.
=> Revert last PR

.ci/test_coverage.sh, CHANGELOG.md
[X] User-visible changes (including notable bug fixes) have been documented in
`CHANGELOG.md`
=> MAINT: CHANGELOG.md updated

.github/workflows/prepare_new_release.yml
suppressing pre-commit verification
=> FIX prepare_new_release workflow

.github/workflows/test_package.yml
Correct test workflow as it was not stopped on failure
=> FIX: tests workflow

.github/workflows/build_docs.yml, .github/workflows/test_package.yml, docs/make.py, spectrochempy/core/readers/importer.py, spectrochempy/utils/file.py, tests/conftest.py
Try to improve speed of tests and build_docs workflow. 
However, there is not really significant improvement but it improves the way data are downloaded!
* TODO: use cache / artifacts
=> workflow speed improvement

.coveragerc, .github/workflows/build_docs.yml, .github/workflows/build_package.yml, .github/workflows/test_package.yml, pytest.ini
When config is in pytest.ini, debug doesn't work in PYCHARM
=> FIX: move coverage setting to test_package.yml

.pre-commit-config.yaml, pyproject.toml
put configuration in pyproject.toml only
=> FIX: autoflake configuration

.pre-commit-config.yaml
=> FIX: isort version in precommit

.github/workflows/test_package.yml
=> FIX: test_package workflow

spectrochempy/core/__init__.py, spectrochempy/plot_preferences.py, spectrochempy/utils/docstrings.py
=> FIX: issue #577

.ci/templates/dependencies.tmpl, .conda/meta.yaml, .github/workflows/test_package.yml, environment.yml, environment_dev.yml, requirements/requirements.txt, requirements/requirements_dev.txt, tests/test_widgets/test_baselinecorrector.py
I didn't find yet what is different since last successful test of the master branch. 
For future comparison, I list explicitly the packages used in the test workflow.
=> FIX: error during nightly build.

.ci/templates/dependencies.tmpl, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, environment_dev.yml, requirements/requirements_dev.txt
=> Prepare_release 0.5.5

docs/_templates/layout.html
shift between LATEST and STABLE not working. Try to fix it.
=> FIX: try to fix redirection between versions

spectrochempy/analysis/_base.py
working with Coord instead of linearCoord (pending full removal of LinearCoord)
=> MAINT: Some revisions / enhancement

tests/test_docs/test_py_in_docs.py
Try to fix problem with windows tests
see
https://github.com/spectrochempy/spectrochempy/pull/650#issuecomment-1551283267
=> FIX: failing test

docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/analysis/_base.py, spectrochempy/application/application.py, tests/test_application.py
Logging is now done only on the console or in string (as used in analysis classes).
=> MAINT: Removing logging to file

spectrochempy/core/dataset/baseobjects/ndarray.py, spectrochempy/core/dataset/nddataset.py, spectrochempy/core/processors/fft.py, spectrochempy/core/readers/read_topspin.py
larmor is now a coord attribute, but was in meta before: take into account this change everywhere.
=> FIX:  larmor related changes

docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/core/dataset/nddataset.py, spectrochempy/core/readers/read_wire.py
Try to solve several problems when slicing multi coordinates
=> FIX: multicoordinate slicing

docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/utils/file.py, tests/test_core/test_writers/test_write_csv.py
=> FIX: issue #706

docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/application/application.py
=> FIX: #716 - removal of exception catching to display full error traceback

docs/userguide/analysis/baseline.py, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/utils/print_versions.py
=> FIX #714: display versions when not using a dev installation.

docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/analysis/decomposition/iris.py, tests/test_analysis/test_decomposition/test_iris.py
add Stejskal-Tanner 
- [x ] User-visible changes (including notable bug fixes) have been documented in `docs/whatsnew/changelog.rst`.
=> IRIS: kernel for PFG NMR

docs/reference/bibliography.bib, docs/reference/papers.rst, spectrochempy/analysis/decomposition/mcrals.py, spectrochempy/analysis/kinetic/kineticutilities.py, spectrochempy/processing/transformation/concatenate.py, spectrochempy/utils/metaconfigurable.py, tests/test_analysis/test_decomposition/test_fast_ica.py
- fix errors related to an update of numpy (in ubuntu and win), see here: https://github.com/spectrochempy/spectrochempy/actions/runs/6600641805/job/17930880105
- fix encodedecode error on github/windows see here: https://github.com/spectrochempy/spectrochempy/actions/runs/6600641805/job/17930880184
- update and reorder citations 
- add a parameter validation in kinetics utilities (see #722)
**Checklist**:
=> Fix errors, update citations

tests/test_analysis/test_kinetic/test_kineticutilities.py
add a test on non isothermal kinetics
**Checklist**:
- [x ] Close the #724
- [x ] Tests have been added
=> test non isothermal kinetics

.github/workflows/build_package.yml
=> fix mambabuild error

.ci/templates/dependencies.tmpl, .conda/meta.yaml, .github/workflows/build_docs.yml, .github/workflows/build_package.yml, .github/workflows/pre-commit.yml, .github/workflows/test_package.yml, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, environment.yml, environment_dev.yml, environment_test.yml, requirements/requirements.txt, requirements/requirements_dev.txt, requirements/requirements_test.txt
=> compatibility with python 3.12

.github/workflows/build_package.yml
=> back to mambabuild

docs/userguide/analysis/mcr_als.py, docs/userguide/analysis/pca.py, docs/userguide/plotting/plotting.py, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/core/dataset/nddataset.py, spectrochempy/core/plotters/plot2d.py, spectrochempy/core/readers/read_omnic.py, spectrochempy/utils/docstrings.py, spectrochempy/utils/plots.py
=> Enhacement #728

.github/workflows/build_docs.yml, .github/workflows/pre-commit.yml, .github/workflows/prepare_new_release.yml, .github/workflows/test_package.yml, docs/whatsnew/index.rst, docs/whatsnew/latest.rst
to avoid warnings, see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> actions to node 20

spectrochempy/analysis/decomposition/mcrals.py
fix an error related to hard modelling of concentration profiles
=> fix MCRALS

.github/workflows/test_package.yml, tests/test_core/test_projects/test_projects.py, tests/test_core/test_readers/test_download.py
bug: testing stops at test-project.  
**Checklist**:
=> fix testing action failure

.ci/templates/dependencies.tmpl, .ci/update_version_and_release_notes.py, .conda/meta.yaml, docs/gettingstarted/install/install_colab.rst, docs/userguide/analysis/fitting.py, docs/userguide/analysis/peak_finding.py, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, environment.yml, environment_dev.yml, environment_test.yml, requirements/requirements.txt, requirements/requirements_dev.txt, requirements/requirements_test.txt, spectrochempy/analysis/peakfinding/peakfinding.py, spectrochempy/core/readers/read_csv.py, spectrochempy/core/units/__init__.py, spectrochempy/core/writers/write_csv.py, spectrochempy/examples/analysis/c_curvefitting/plot_lstsq_single_equation.py, spectrochempy/utils/plots.py, tests/test_core/test_dataset/test_coord.py, tests/test_core/test_dataset/test_coordset.py, tests/test_core/test_dataset/test_issues_dataset.py, tests/test_core/test_dataset/test_ndarray.py, tests/test_core/test_dataset/test_ndmath.py, tests/test_core/test_readers/test_read_omnic.py, tests/test_core/test_units/test_units.py
=> fix compatibility with pint

docs/reference/bibliography.bib, docs/userguide/processing/denoising.py, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/processing/filter/denoise.py
improves speed of default method and add a new one
**Checklist**:
- [ x] Example have been added
- [x ] User-visible changes (including notable bug fixes) have been documented in `docs/whatsnew/changelog.rst`.
=> improves despike()

.github/workflows/build_docs.yml, docs/whatsnew/changelog.rst, docs/whatsnew/latest.rst, spectrochempy/analysis/decomposition/mcrals.py, tests/test_analysis/test_decomposition/test_mcrals.py
allows storing the C and St generated at each iteration (storeIteration parameter)
**Checklist**:
=> MCRALS: store C and St history

.github/workflows/install_on_colab.yml, .pre-commit-config.yaml
test install on the latest docker image of google Colab.
Would allow to detect errors such as  #784 and #772
=> github action to test install on google Colab

docs/make.py
Should now give more interesting information on google search results page
**Checklist**:
=> FIX #798: redirection page at spectrochempy.fr startup

.pre-commit-config.yaml, docs/conf.py, docs/make.py, docs/sources/index.rst, docs/sources/index.rst.tmpl, docs/sources/userguide/introduction/interface.py, docs/sources/userguide/introduction/mdcheatsheet.py, docs/sources/userguide/objects/dataset/dataset.py, docs/sources/userguide/processing/transformations.py, recipe/meta.yaml, src/spectrochempy/analysis/decomposition/simplisma.py, src/spectrochempy/core/dataset/arraymixins/ndio.py, src/spectrochempy/core/dataset/arraymixins/ndmath.py, src/spectrochempy/examples/analysis/a_decomposition/plot_simplisma.py, src/spectrochempy/processing/baselineprocessing/baselineprocessing.py, tests/test_analysis/test_decomposition/test_simplisma.py
- Use --single-doc option on make.py to build a single page. (developper doc will be updated to describe the process)
- Use --no-api option to build without the API reference generation. 
This speedup the build for checking website aspect for instance.
=> Single doc building 

docs/sources/userguide/objects/dataset/dataset.py
**Checklist**:
if you have one) in the zenodo.json in the field contributors field. _Be careful
[JSON Validator](https://jsonformatter.curiousconcept.com/))_
=> fix documentation on coord

README.md, docs/conf.py, docs/make.py
This pull request includes updates to the `README.md`, `docs/conf.py`, and `docs/make.py` files to improve documentation and configuration settings. The most important changes include updating links in the `README.md`, adding configuration settings for RST files in `docs/conf.py`, and adding a filter condition in `docs/make.py`.
=> FIX: readme

docs/sources/reference/bibliography.bib, docs/sources/reference/papers.rst, docs/sources/whatsnew/changelog.rst, docs/sources/whatsnew/latest.rst, src/spectrochempy/analysis/decomposition/mcrals.py, src/spectrochempy/application/info.py, src/spectrochempy/core/readers/read_omnic.py
- fix mcrals: lists of intermediate St matrices now available
- update omnic__reader
- update bibliography
- update contributors
=> fixes and update

.github/workflows/pre-commit.yml, .github/workflows/test_package.yml, docs/sources/gettingstarted/install/index.rst, docs/sources/gettingstarted/install/install_mac_linux.rst, docs/sources/gettingstarted/install/install_win.rst, docs/sources/gettingstarted/quickstart.py, docs/sources/whatsnew/changelog.rst, docs/sources/whatsnew/latest.rst, pyproject.toml, src/spectrochempy/core/dataset/nddataset.py
- minimum python version fixed to 3.11 (instead of 3.10) as  latest numpy version (2.3.0) suppports python 3.11-3.13
- fix issue 875
**Checklist**:
=> fix issue 875
